name: query-mix
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11.13
  - pip
  - cudatoolkit=11.8
  - faiss-gpu=1.8.0
  - blas=1.0=mkl
  - mkl
  - numpy=1.26.4
  - pip:
      - -r requirements.txt
